### ISSUE TITLE
Feature request: settings paragraph

### ISSUE THREAD

**Issue by sbdobrescu** [BamaRayne/Echosistant#20]
Instead of creating a web page that would make Echosistant look like Ask Alexa, create a dynamic paragraph that lists pCommands, pDevices, pProfile for the Main skill custom slots

**Comment by sbdobrescu** [comment]
This would require a new toggle and section under Settings and security, which would unhide the list of items that need to be copied and pasted into the custom slots

**Comment by BamaRayne** [comment]
The list would need to show in the Live Logs but its not going to be in a format that is easily pasted into the skill

**Comment by sbdobrescu** [comment]
In progress

**Comment by sbdobrescu** [comment]
done!
