### ISSUE TITLE
Disable alerts not disabling

### ISSUE THREAD

**Issue by sbdobrescu** [BamaRayne/Echosistant#28]
If configured, but the toggle is disabled, the alerts continue to be sent. The toggle should mute the alerts even if configured...

**Comment by BamaRayne** [comment]
I agree with this.... just haven't figured out how to clear them when it's turned off.... but, leaving it the way it is you can close the section and keep the UI clean.

**Comment by BamaRayne** [comment]
I can build in a disable toggle to each of the alerts for a quick disable and then a master stop all alerts in the settings section.....

**Comment by BamaRayne** [comment]
I built in kill switches.  you can turn off all notifications or pick and choose the ones you want on/off.
