### ISSUE TITLE
CoRE integration is broken

### ISSUE THREAD

**Issue by sbdobrescu** [BamaRayne/Echosistant#3]
Missing data variable on child. It is required to pass data for import

**Comment by sbdobrescu** [comment]
Solution: add this variable in the " SPEECH AND TEXT PROCESSING" block 

def data = [args: tts ]

E.G.

def profileEvaluate(params) {
        def tts = params.ptts
        def txt = params.pttx
        def intent = params.pintentName
        def childName = app.label
        **def data = [args: tts ]**

**Comment by BamaRayne** [comment]
Completed
