### ISSUE TITLE
Pre defined alert messages

### ISSUE THREAD

**Issue by sbdobrescu** [BamaRayne/Echosistant#31]
Need default alert messages with custom override if a message is typed in the box. Most people will stay with device name is on/off/active/inactive....

**Comment by BamaRayne** [comment]
This is where we need the variables.... One alert can have multiple devices chosen and it can play the device name and message.... instead of multiple profiles, it can all be done in one.

**Comment by sbdobrescu** [comment]
That is not in the code, the proc doesn't know which device was active, it only knows that an active event happened...

**Comment by BamaRayne** [comment]
i put the variable in the code last night.  I'll build in a list of defaults for each of the notifications.  This allows the user to have a quick setup procedure too.

**Comment by sbdobrescu** [comment]
Dropping the idea. Closing ticket
