### ISSUE TITLE
Use case: motion off

### ISSUE THREAD

**Issue by sbdobrescu** [BamaRayne/Echosistant#32]
Alexa tell Assistant to stop turning the lights off in the kitchen

Utterance: main pcommand turning light off in the pprofile

**Comment by BamaRayne** [comment]
This is something we can work into the system when we start building the rule builder

**Comment by BamaRayne** [comment]
This can be done easier with the CoRE integration....

create a virtual switch.  Setup a profile "kitchen motion".  have the switch turn toggle when the profile is run.

Alexa, tell home to stop the kitchen motion.  VS turns on.  Piston is disabled
Alexa, tell home to start the kitchen motion in 30 minutes.  Piston enables in 30 minutes.

**Comment by sbdobrescu** [comment]
Command stop added, utterance is pcommand the pdevice, where pdevuce is the virtual switch.
