### ISSUE TITLE
Use case: get the party started 

### ISSUE THREAD

**Issue by sbdobrescu** [BamaRayne/Echosistant#33]
Alexa tell assistant to get the party started

Utterance: main get the pprofile started

Where party is a profile. This can be used for other Routine type of profiles.

Alt Utterance main start pprofile (party, bed time, dinner, etc)

**Comment by BamaRayne** [comment]
This was what I was trying to do the other night... with the Goodnight Profile.....

**Comment by sbdobrescu** [comment]
Had very mixed results getting Alexa to recognize the correct profile name. This functionality is now active
