### ISSUE TITLE
Notifications Push msg 

### ISSUE THREAD

**Issue by BamaRayne** [BamaRayne/Echosistant#41]
this is not working.

**Comment by sbdobrescu** [comment]
proc missing...each alert has to have 

if (push1) sendtxt (eTxt)
if (notify1) sendtxt (eTxt)

Also this line under SMS handler is not correct:

    	if (push || push1 || push2 || push3 || push4 || push5 || push6 || push7) { 
    		sendPush message


What is says is if ANY of those fields are populated, then send a push. So this will send a push for a text message, even if the push toggle is not enabled...

**Comment by sbdobrescu** [comment]
Fixed
