### ISSUE TITLE
FEATURES

### ISSUE THREAD

**Issue by BamaRayne** [BamaRayne/Echosistant#53]
Add to this list of Features as they are put in the program

**Security Pin** - "Alexa, tell Home to Active Pin Number for (Locks) or (Doors) or (Thermostats)

**Continued Commands** "Conversational Features" - To activate, just say "Alexa, tell Home to Start the Conversation"...... to turn off just say, "Alexa, tell Home to Stop the Conversation"

**HVAC FILTERS REMINDER**  just say, Alexa, tell home I replaced the filters.

**Security Device**  use virtual switch to set delay on shm.  Use security pin to arm and disarm.

Yes, still messing around with feedback....

Write this down fr the Wiki...

Alexa, what < group > are < command > at < intent >

Alexa, what lights are on in the Kitchen

Alexa what LIGHTS are ON in MY HOME (My Home is a skill)

**Comment by sbdobrescu** [comment]
Feedback: Alexa ask HOME when was < device name > last  < past tense verb >  will trigger custom response from Alexa using the verb as action, as long as the past tense verb is added to the LIST OF OPERANDS. 

Example: 
Me: Alexa ask HOME when was 'desk light' last fed? 
Alexa: The Desk Light was last fed at 4:30 AM (where time stamp is the device last updated status)

**Comment by BamaRayne** [comment]
I think we've done all of this
