### ISSUE TITLE
EchoSistantLabs - Pin for Locks failure

### ISSUE THREAD

**Issue by BamaRayne** [BamaRayne/Echosistant#57]
Program is not acknowledging the correct PIN once activated.
see bottom picture first and read logs from bottom to top.

![image](https://cloud.githubusercontent.com/assets/14341760/21873459/356bac86-d834-11e6-8063-578932c13004.png)

![image](https://cloud.githubusercontent.com/assets/14341760/21873426/049ad0f0-d834-11e6-8aff-cce5efe4d69f.png)

**Comment by sbdobrescu** [comment]
In all of my tests pin number was returned either via the command or the pin slot. Of course yours returned via number slot. I really don't like how inconsistent Alexa buckets things. I'll add the number slot into validation process. Geez

**Comment by sbdobrescu** [comment]
This has been taken care of, closing ticket
