### ISSUE TITLE
EchoSistantLabs - Fan command failure

### ISSUE THREAD

**Issue by BamaRayne** [BamaRayne/Echosistant#58]
Set ceiling fan to low, med, high works.  

speed up/slow down does not work
set to level does not work

Commands are not actually being sent to the device.  There are no logs for the device when these commands are sent.

![image](https://cloud.githubusercontent.com/assets/14341760/21873600/46df33e2-d835-11e6-9632-ab3e8dc59e78.png)

**Comment by sbdobrescu** [comment]
bug fixed, closing ticket
