### ISSUE TITLE
Labs update 1st Feb

### ISSUE THREAD

**Issue by TimRaynor** [BamaRayne/Echosistant#78]
When turning off a light I get the response "ok turning off Living Room Light, would you like to try again" 

I think this response works better when adjusting brightness but don't think it sounds correct for on and off commands.

**Comment by TimRaynor** [comment]
Groovy code has spelling mistakes of "battery" and "feedback" in lines 170 and 171

**Comment by sbdobrescu** [comment]
Both problens have been resolved.
