### ISSUE TITLE
After creating SmartApp Echo: EchoSistant it is not showing up on marketplace->myApps

### ISSUE THREAD

**Issue by naseemr** [BamaRayne/Echosistant#80]
I have followed the instruction for nnstalling the ExhoSistant app and now tying to install in my device mobile app. When I select MyApps, I do not see EchoSistant.  Please help.
Thanks,

**Comment by sbdobrescu** [comment]
Sorry for the late response. If you didn't figure out the problem, you may need to first publish the Main app. If the problem persists, please reach out to us on the community.
